### PR TITLE
Support formatter options

### LINKED ISSUE #15: Formatter Feature in ApexCharts Options
It appears the "formatter" feature in the options don't work. Is that intentional and any plans integrating that feature?

### PR DESCRIPTION
**Pull request by glennjacobs**
Closes #15 #16 

This pull request looks to add the ability to use formatters in the Apex chart options.

This is important as charts are often used for monetary values and therefore want to be formatted as such.

E.g. `123456.0` vs `$123,456.00`

You can now do something like the following

```php
'labels' => [
    'formatter' => 'function (value) { return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value); }',
],
```

### CODE REVIEW

**Comment by glennjacobs** [comment]
Converted to draft as there seems to be an issue with the auto-refresh.

**Comment by glennjacobs** [comment]
This should be good now.

**Comment by leandrocfe** [comment]
Thank you, but I used RawJs to make it
https://github.com/leandrocfe/filament-apex-charts?tab=readme-ov-file#extra-options-and-formatters

**Comment by glennjacobs** [comment]
> Thank you, but I used RawJs to make it
> 
> https://github.com/leandrocfe/filament-apex-charts?tab=readme-ov-file#extra-options-and-formatters

Ok cool. I'll check it out.

**Pull request closed without merging**
