### PR TITLE
Fix duplicate database queries

### PR DESCRIPTION
**Pull request by howdu**

### CODE REVIEW

**Comment by billmn** [comment]
@leandrocfe Can this PR be merged?

**Comment by leandrocfe** [comment]
> @leandrocfe Can this PR be merged?

Hi,
Sure. Could you explain this issue please?

**Comment by billmn** [comment]
> > @leandrocfe Can this PR be merged?
> 
> Hi, Sure. Could you explain this issue please?

Without this change the `getOptions` method was called twice, so we have duplicated queries for every chart.

**Comment by leandrocfe** [comment]
> > > @leandrocfe Can this PR be merged?
> > 
> > Hi, Sure. Could you explain this issue please?
> 
> Without this change the `getOptions` method was called twice, so we have duplicated queries for every chart.

Ok, I'll check. Thank you 👍

**Comment by billmn** [comment]
@leandrocfe Great, thank you!

**Pull request merged**
